# Generated by Django 4.1.5 on 2023-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Hwidth', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('Lstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
